// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @dev Matches Groth16Verifier.verifyProof's signature exactly (generated by
/// `snarkjs zkey export solidityverifier` — see zk/circuits/match.circom).
interface IGroth16Verifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[3] calldata _pubSignals
    ) external view returns (bool);
}

/// @notice Tamper-evident anchor for off-chain evidence bundles.
/// @dev Stores no personal data — only keccak256 digests of canonicalised JSON.
contract EvidenceAnchor {
    event Anchored(
        bytes32 indexed digest,
        address indexed attester,
        uint64  timestamp,
        string  cid          // IPFS CIDv1 of the full bundle
    );
    event BatchAnchored(bytes32 indexed merkleRoot, address indexed attester, uint64 timestamp, uint32 leaves);
    event Revoked(bytes32 indexed consentDigest, address indexed revoker, uint64 timestamp);

    error AlreadyAnchored(bytes32 digest);
    error AlreadyRevoked(bytes32 consentDigest);
    error BadProof();

    mapping(bytes32 => uint64) public anchoredAt;

    /// @notice Bidirectional to `anchoredAt`: the anchor is permanent, but the
    /// subject holds a permanent, publicly auditable, timestamped veto over
    /// its use (PRD §7.3) — closer to what DPDP §12 / GDPR Art. 17 actually
    /// ask for than silent deletion, since a hash can't be un-anchored anyway.
    mapping(bytes32 => uint64) public revokedAt;

    /// @dev address(0) disables the ZK path — anchor()/verify()/revoke() work
    /// regardless (PRD §7.1's L0/L1 rungs don't need a verifier at all).
    IGroth16Verifier public immutable verifier;

    constructor(address _verifier) {
        verifier = IGroth16Verifier(_verifier);
    }

    function anchor(bytes32 digest, string calldata cid) external {
        if (anchoredAt[digest] != 0) revert AlreadyAnchored(digest);
        anchoredAt[digest] = uint64(block.timestamp);
        emit Anchored(digest, msg.sender, uint64(block.timestamp), cid);
    }

    /// @notice One tx anchors N discoveries; verify a leaf with a Merkle proof.
    function anchorBatch(bytes32 merkleRoot, uint32 leaves) external {
        if (anchoredAt[merkleRoot] != 0) revert AlreadyAnchored(merkleRoot);
        anchoredAt[merkleRoot] = uint64(block.timestamp);
        emit BatchAnchored(merkleRoot, msg.sender, uint64(block.timestamp), leaves);
    }

    function verify(bytes32 digest) external view returns (bool ok, uint64 ts) {
        ts = anchoredAt[digest];
        ok = ts != 0;
    }

    /// @notice Revokes a previously-anchored consent artifact digest (PRD §3/§7.3).
    /// Anyone can call `revoke` — the digest alone carries no ability to
    /// distinguish subject from attacker on-chain, exactly like `anchor` itself;
    /// the trust model here is the same as the base anchor (off-chain
    /// attribution via whoever controls the signing key), not a new one.
    function revoke(bytes32 consentDigest) external {
        if (revokedAt[consentDigest] != 0) revert AlreadyRevoked(consentDigest);
        revokedAt[consentDigest] = uint64(block.timestamp);
        emit Revoked(consentDigest, msg.sender, uint64(block.timestamp));
    }

    function consentStatus(bytes32 consentDigest) external view returns (bool revoked, uint64 ts) {
        ts = revokedAt[consentDigest];
        revoked = ts != 0;
    }

    /// @notice Anchors `digest` only if `pubSignals` (the Poseidon commitments
    /// and threshold — PRD §7.1) verify against a real Groth16 proof. The
    /// chain itself refuses to record a score nobody actually proved.
    function anchorWithProof(
        bytes32 digest,
        string calldata cid,
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[3] calldata pubSignals
    ) external {
        if (!verifier.verifyProof(a, b, c, pubSignals)) revert BadProof();
        if (anchoredAt[digest] != 0) revert AlreadyAnchored(digest);
        anchoredAt[digest] = uint64(block.timestamp);
        emit Anchored(digest, msg.sender, uint64(block.timestamp), cid);
    }
}
